# Generated by Django 2.2 on 2021-03-17 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=post.models.PostModel.image_path)),
                ('visibility', models.CharField(blank=True, choices=[('public', 'Public'), ('only me', 'Only Me')], default='Public', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('no_of_like', models.IntegerField(default=0)),
                ('no_of_comments', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
