# Generated by Django 2.2 on 2021-03-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_forgetpasswordotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpasswordotp',
            name='expired_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
