# Generated by Django 2.2 on 2021-03-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210316_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileactivation',
            name='expired_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
